Break out wget and curl commands to get SSG zip

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,7 +27,13 @@ before_script:
 script:
   - ./build-for-osx.sh
 # Parse release page json to obtain link to latest content zip file and download it
-  - wget `curl -s https://api.github.com/repos/ComplianceAsCode/content/releases/latest?access_token=$GITHUB_TOKEN | jq -r ".assets[] | select(.name | test(\"(scap-security-guide-[0-9].[0-9].[0-9]*).zip\")) | .browser_download_url"` -O ssg.zip
+  - |
+    DWN_LINK=`curl -s https://api.github.com/repos/ComplianceAsCode/content/releases/latest?access_token=$GITHUB_TOKEN | jq -r ".assets[] | select(.name | test(\"(scap-security-guide-[0-9].[0-9].[0-9]*).zip\")) | .browser_download_url"`
+    if [ -z "${DWN_LINK}" ] ; then
+        echo "Could not get the ZIP URL! It is empty!"
+        exit 1
+    fi
+  - wget "${DWN_LINK}" -O ssg.zip
   - mkdir -p `pwd`/build-osx/scap-workbench.app/Contents/Resources/ssg/ && unzip ssg.zip && cp -a scap-security-guide-*/* `pwd`/build-osx/scap-workbench.app/Contents/Resources/ssg/
   - cd build-osx && sh osx-create-dmg.sh
 
